export const calculatorKeys = [
  {
    id: "clear",
    description: "Clear(Esc)",
    label: "C",
    type: "other",
  },
  {
    id: "negate",
    description: "Negatate the displayed value",
    label: "+/-",
    type: "other",
  },
  {
    id: "percent",
    description: "Percent (or press %)",
    label: "%",
    type: "other",
  },
  {
    id: "divide",
    description: "Divide (or press /)",
    label: "\u00F7",
    type: "operator",
  },
  {
    id: "seven",
    description: "",
    label: "7",
    type: "number",
  },
  {
    id: "eight",
    description: "",
    label: "8",
    type: "number",
  },
  {
    id: "nine",
    description: "",
    label: "9",
    type: "number",
  },
  {
    id: "multiply",
    description: "Multiple (or press *)",
    label: "\u00D7",
    type: "operator",
  },
  {
    id: "four",
    description: "",
    label: "4",
    type: "number",
  },
  {
    id: "five",
    description: "",
    label: "5",
    type: "number",
  },
  {
    id: "six",
    description: "",
    label: "6",
    type: "number",
  },
  {
    id: "subtract",
    description: "Subtract (or press -)",
    label: "\u2212",
    type: "operator",
  },
  {
    id: "one",
    description: "",
    label: "1",
    type: "number",
  },
  {
    id: "two",
    description: "",
    label: "2",
    type: "number",
  },
  {
    id: "three",
    description: "",
    label: "3",
    type: "number",
  },
  {
    id: "add",
    description: "Add (or press +)",
    label: "\u002B",
    type: "operator",
  },
  {
    id: "zero",
    description: "",
    label: "0",
    type: "number",
  },
  {
    id: "dot",
    description: "",
    label: ".",
    type: "number",
  },
  {
    id: "equal",
    description: "Equal (or press Return)",
    label: "\u003D",
    type: "operator",
  },
];
